### ISSUE TITLE
what goes in attributes file?

### ISSUE THREAD

**Issue by ejaronne** [mitre/aws-rds-oracle-mysql-ee-5.7-cis-baseline#4]
Update README to reflect what the user needs to define in the attributes file. Note that currently the inspec.yml of the overlay is not respected by the dependent baseline (i.e., the dependent baseline's inspec.yml values apply, not the overlay's.) Hence, the need for an attributes file at this time. Use https://github.com/mitre/docs-mitre-inspec/blob/master/templates/baseline_readme.md and it's "The following attributes must be configured in an attributes file..." section and the "Running this profile..." section style.

**Comment by ejaronne** [comment]
Shouldn't this local run command also use the attributes file?

$ inspec exec aws-rds-oracle-mysql-ee-5.7-cis-baseline --reporter cli json:output.json

**Comment by asturtevant** [comment]
Updated the readme to close this
